### PR TITLE
fixes filters function

### PR DESCRIPTION
**Pull request by ghost**
@Prefinem

### CODE REVIEW

**Comment by Raxvis** [comment]
I am going to merge this in, but in the future, if you do a `yarn` command in the folder, eslint and such should work on cleaning things up

**Comment by ghost** [comment]
what do you mean i should do a yarn command?

**Comment by Raxvis** [comment]
Do you use yarn or npm?

**Comment by ghost** [comment]
I use yarn. I think I got confused you were saying I should do something on GitHub with my pull requests lol. But I guess what you actually meant is I can pull the latest copy using yarn?

**Comment by Raxvis** [comment]
No, I meant that before you commit your code, you should run `yarn` in the folder.  That way `yarn staged` will get run by husky

**Comment by ghost** [comment]
my bad :D

**Comment by Raxvis** [comment]
No worries!  Just some stuff to help you out.

**Comment by milezzz** [comment]
Great work! Going to give this another shot with these bugs worked out =]

**Pull request merged**
